from toolkit_common import LANGUAGES, load_toolkit_settings, save_language

S = {
"en":{"file":"File","refresh":"Refresh","exit":"Exit","view":"View","theme":"Theme","settings":"Settings","language":"Language","help":"Help","guide":"User Guide","folder":"Open Toolkit Folder","about":"About Broadcast Scheduler","search":"Search:","group":"Group:","all":"All","conflicts_only":"Only Conflicts","previous":"◀ Previous Week","today":"Today","next":"Next Week ▶","events":"Events","calendar":"Calendar","public":"Public Calendar","status":"Status","start":"Start","event":"Event","conflicts":"Conflicts","runtimes":"RunTimes","week":"Week","created":"Created by Raymond Ummels","assistance":"Developed with assistance from OpenAI ChatGPT"},
"de":{"file":"Datei","refresh":"Aktualisieren","exit":"Beenden","view":"Ansicht","theme":"Design","settings":"Einstellungen","language":"Sprache","help":"Hilfe","guide":"Benutzerhandbuch","folder":"Toolkit-Ordner öffnen","about":"Über Broadcast Scheduler","search":"Suche:","group":"Gruppe:","all":"Alle","conflicts_only":"Nur Konflikte","previous":"◀ Vorherige Woche","today":"Heute","next":"Nächste Woche ▶","events":"Ereignisse","calendar":"Kalender","public":"Öffentlicher Kalender","status":"Status","start":"Start","event":"Ereignis","conflicts":"Konflikte","runtimes":"Laufzeiten","week":"Woche","created":"Erstellt von Raymond Ummels","assistance":"Entwickelt mit Unterstützung von OpenAI ChatGPT"},
"nl":{"file":"Bestand","refresh":"Vernieuwen","exit":"Afsluiten","view":"Beeld","theme":"Thema","settings":"Instellingen","language":"Taal","help":"Help","guide":"Gebruikershandleiding","folder":"Toolkit-map openen","about":"Over Broadcast Scheduler","search":"Zoeken:","group":"Groep:","all":"Alle","conflicts_only":"Alleen conflicten","previous":"◀ Vorige week","today":"Vandaag","next":"Volgende week ▶","events":"Gebeurtenissen","calendar":"Kalender","public":"Openbare kalender","status":"Status","start":"Start","event":"Gebeurtenis","conflicts":"Conflicten","runtimes":"Uitvoeringen","week":"Week","created":"Gemaakt door Raymond Ummels","assistance":"Ontwikkeld met hulp van OpenAI ChatGPT"},
"bg":{"file":"Файл","refresh":"Обновяване","exit":"Изход","view":"Изглед","theme":"Тема","settings":"Настройки","language":"Език","help":"Помощ","guide":"Ръководство","folder":"Отваряне на папката","about":"За Broadcast Scheduler","search":"Търсене:","group":"Група:","all":"Всички","conflicts_only":"Само конфликти","previous":"◀ Предишна седмица","today":"Днес","next":"Следваща седмица ▶","events":"Събития","calendar":"Календар","public":"Публичен календар","status":"Статус","start":"Начало","event":"Събитие","conflicts":"Конфликти","runtimes":"Изпълнения","week":"Седмица","created":"Създадено от Raymond Ummels","assistance":"Разработено с помощта на OpenAI ChatGPT"}}

def language(): return load_toolkit_settings()["language"]
def tr(key): return S.get(language(), S["en"]).get(key, key)
