#!/usr/bin/env python3
"""
=========================================================
 Audio Library Toolkit
---------------------------------------------------------
 Tool      : Auto Cutter
 Version   : 0.1.0
 Author    : Raymond Ummels
 License   : MIT
=========================================================

Reads silence_report.csv generated by Silence Scanner.

Workflow

Silence Scanner
        │
        ▼
silence_report.csv
        │
        ▼
Auto Cutter
        │
        ▼
Music_Cut

Changes in v0.3.3

- Completely rewritten cutting engine
- Cleaner FFmpeg handling
- Better validation
- Improved logging
"""

import csv
import os
import subprocess
import sys
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================

VERSION = "1.0.0"

FFMPEG  = r"C:\ffmpeg\ffmpeg.exe"
FFPROBE = r"C:\ffmpeg\ffprobe.exe"

CSV_FILE = "silence_report.csv"

OUTPUT_FOLDER = "Music_Cut"

BITRATE = "320k"

KEEP_START = 0.20
KEEP_END   = 0.20

# Console output

SHOW_FFMPEG = False

SUBPROCESS_FLAGS = (
    subprocess.CREATE_NO_WINDOW
    if os.name == "nt"
    else 0
)

# =========================================================
# Helper
# =========================================================

def die(message):
    print()
    print("ERROR")
    print(message)
    sys.exit(1)


def ffmpeg_exists():
    return os.path.isfile(FFMPEG)

def ffprobe_exists():
    return os.path.isfile(FFPROBE)

def csv_exists():

    return os.path.isfile(CSV_FILE)


# =========================================================
# Startup checks
# =========================================================

if not ffmpeg_exists():
    die(f"FFmpeg not found:\n{FFMPEG}")

if not ffprobe_exists():
    die(f"FFprobe not found:\n{FFPROBE}")

if not csv_exists():
    die(f"CSV not found:\n{CSV_FILE}")

# =========================================================
# Read CSV
# =========================================================

with open(
    CSV_FILE,
    newline="",
    encoding="utf-8-sig"
) as file:

    rows = list(csv.DictReader(file, delimiter=";"))

if not rows:
    die("CSV is empty.")

# =========================================================
# Output folder
# =========================================================

first_file = rows[0]["File"]

music_root = Path(first_file).parent.parent

output_dir = music_root / OUTPUT_FOLDER

output_dir.mkdir(exist_ok=True)

# =========================================================
# Runtime data
# =========================================================

seen_files = set()

created = 0
skipped = 0
errors = 0

report = []

print("=" * 58)
print("Audio Library Toolkit")
print(f"Auto Cutter v{VERSION}")
print("=" * 58)
print()

print(f"Files in CSV : {len(rows)}")
print(f"Output Folder: {output_dir}")
print()
# =========================================================
# Audio helper functions
# =========================================================

def get_duration(filename):
    """
    Returns duration in seconds using FFprobe.
    """
    cmd = [
        FFPROBE,
        "-v","error",
        "-show_entries","format=duration",
        "-of","default=noprint_wrappers=1:nokey=1",
        filename
    ]

    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
        creationflags=SUBPROCESS_FLAGS
    )

    if result.returncode != 0:
        return None

    try:
        return float(result.stdout.strip())
    except ValueError:
        return None


# =========================================================
# Calculate cut positions
# =========================================================

def calculate_times(row, duration):

    intro = 0.0
    outro = 0.0

    problem = row["Problem"].upper()

    if "LONG INTRO" in problem:

        intro = max(
            0.0,
            float(row["Intro"]) - KEEP_START
        )

    if "BAD OUTRO" in problem:

        outro = max(
            0.0,
            float(row["Outro"]) - KEEP_END
        )

    end_time = duration - outro

    if end_time <= intro:

        return None

    return (
        round(intro, 3),
        round(end_time, 3)
    )


# =========================================================
# FFmpeg cutter
# =========================================================

def cut_audio(src, dst, start_time, end_time):

    cut_duration = max(0.0, end_time - start_time)

    cmd = [
        FFMPEG,
        "-hide_banner",
        "-loglevel","error",
        "-y",
        "-i", src,
        "-ss", f"{start_time:.3f}",
        "-t", f"{cut_duration:.3f}",
        "-map_metadata","0",
        "-map","0:a:0",
        "-c:a","libmp3lame",
        "-b:a",BITRATE,
        dst
    ]

    if SHOW_FFMPEG:
        print(" ".join(cmd))

    result = subprocess.run(cmd, creationflags=SUBPROCESS_FLAGS)

    if result.returncode != 0:
        return False

    if not os.path.isfile(dst):
        return False

    if os.path.getsize(dst) == 0:
        return False

    return True
    # =========================================================
# Main processing loop
# =========================================================

for index, row in enumerate(rows, start=1):

    source = row["File"]

    filename = os.path.basename(source)

    print(f"[{index}/{len(rows)}] {filename}", flush=True)

    # -----------------------------------------------------

    if os.path.abspath(source).lower() in seen_files:

        report.append([
            filename,
            "SKIPPED",
            "Duplicate filename"
        ])

        skipped += 1

        continue

    seen_files.add(os.path.abspath(source).lower())

    # -----------------------------------------------------

    if not os.path.isfile(source):

        report.append([
            filename,
            "ERROR",
            "Source file missing"
        ])

        errors += 1

        continue

    # -----------------------------------------------------

    duration = get_duration(source)

    if duration is None:

        report.append([
            filename,
            "ERROR",
            "Could not determine duration"
        ])

        errors += 1

        continue

    # -----------------------------------------------------

    cut = calculate_times(row, duration)

    if cut is None:

        report.append([
            filename,
            "SKIPPED",
            "Nothing to cut"
        ])

        skipped += 1

        continue

    start_time, end_time = cut

    # -----------------------------------------------------

    destination = output_dir / filename

    if destination.exists():

        report.append([
            filename,
            "SKIPPED",
            "Already exists"
        ])

        skipped += 1

        continue

    # -----------------------------------------------------

    success = cut_audio(

        str(source),
        str(destination),
        start_time,
        end_time

    )

    if success:

        created += 1

        report.append([
            filename,
            "CREATED",
            f"Intro={start_time:.2f}s  Outro={duration-end_time:.2f}s"
        ])

    else:

        errors += 1

        report.append([
            filename,
            "ERROR",
            "FFmpeg failed"
        ])
        # =========================================================
# Write report
# =========================================================

report_file = "cut_report.csv"

with open(
    report_file,
    "w",
    newline="",
    encoding="utf-8-sig"
) as csvfile:

    writer = csv.writer(csvfile, delimiter=";")

    writer.writerow([
        "File",
        "Status",
        "Message"
    ])

    writer.writerows(report)

# =========================================================
# Summary
# =========================================================

print()
print("=" * 58)
print("Finished")
print("=" * 58)

print(f"Created : {created}")
print(f"Skipped : {skipped}")
print(f"Errors  : {errors}")

print()
print(f"Output Folder : {output_dir}")
print(f"Report        : {report_file}")

print()

if errors == 0:
    print("Finished successfully.")
else:
    print("Finished with errors.")

print()
print("=" * 58)

sys.exit(1 if errors else 0)
